Testing code for reset.R and unit-test for reset functions
kar-agg-gen/DGEobj pull request #9
Opened 2020-10-28 13:35 UTC by kar-agg-gen

2020-10-30 14:43 UTC, saranya-ag requested changes

2020-10-30 14:43 UTC, saranya-ag commented on tests/testthat/test_reset.R
> +    # checking DGEobj with wrong counts matirx
Rephrase comment to Testing DGEobj without count Matrix. 
Typo - Matrix

2020-10-30 14:43 UTC, saranya-ag commented on tests/testthat/test_reset.R
> +    names(test_DGEobj) <- c( "counts_orig" , "counts", "design_orig" , "design", "peptideAnnotation_orig")
Extra space before counts_orig

2020-10-30 14:43 UTC, saranya-ag commented on tests/testthat/test_reset.R
> +    names(test_DGEobj) <- c( "counts_orig" , "counts", "design_orig" , "design", "isoformData_orig")
Extra space before counts_orig

2020-10-30 14:43 UTC, saranya-ag commented on tests/testthat/test_reset.R
> +    # Expecting warning as current object could not build the GRanges object!
Rephrase comment 

Warning expected as the current object cannot build the GRanges object.

2020-10-30 14:43 UTC, saranya-ag commented on R/reset.R
> +    metaList <- getBaseType(dgeObj, "meta")[1:3]
Can you check this - MetaList is not being used anywhere

2020-10-31 00:26 UTC, saranya-ag approved these changes

2020-11-20 21:37 UTC, kar-agg-gen commented
closing PR as changes are already merged

2020-11-20 21:37 UTC, closed without merging